GET http://localhost:3001/
###
GET http://localhost:3001/api/users/654237ee603900bc3c3fa1b1/
###
GET http://localhost:3001/api/users/654237ee603900bc3c3fa1b1/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IndhbGRlcmhhd2siLCJpZCI6IjY1NDIzN2VlNjAzOTAwYmMzYzNmYTFiMSIsImlhdCI6MTY5ODgzODc5MH0.v2i3swOq6oU6LL_zgK1uKVsubZ3AROUMVT27I_HN7m0
###
GET http://localhost:3001/api/abonements/
###
GET http://localhost:3001/api/abonements/user
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IndhbGRlcmhhd2siLCJpZCI6IjY1NDIzN2VlNjAzOTAwYmMzYzNmYTFiMSIsImlhdCI6MTY5ODgzODc5MH0.v2i3swOq6oU6LL_zgK1uKVsubZ3AROUMVT27I_HN7m0
###
POST http://localhost:3001/api/abonements/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJ1bGJhYiIsImlkIjoiNjU0OTJkZGNmY2YyZGFiOWE2ZmFmYzMzIiwiaWF0IjoxNjk5NDcxODY5fQ.BHJkYA5UOfgUMHfF5FVGYv6nstER4IekVYML2Lk3Cg8

{
    "amount": 12,
    "price": 2700
}
###
POST http://localhost:3001/api/abonements/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IndhbGRlcmhhd2siLCJpZCI6IjY1NDIzN2VlNjAzOTAwYmMzYzNmYTFiMSIsImlhdCI6MTY5ODgzODc5MH0.v2i3swOq6oU6LL_zgK1uKVsubZ3AROUMVT27I_HN7m0

{
    "amount": 4,
    "price": 1300
}
###
PUT http://localhost:3001/api/abonements/65423b39603900bc3c3fa22a/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IndhbGRlcmhhd2siLCJpZCI6IjY1NDIzN2VlNjAzOTAwYmMzYzNmYTFiMSIsImlhdCI6MTY5ODgzODc5MH0.v2i3swOq6oU6LL_zgK1uKVsubZ3AROUMVT27I_HN7m0

{
    "updateType": "activation"
}
###
GET http://localhost:3001/api/users/
###
POST http://localhost:3001/api/users/
content-type: application/json

{
    "username": "walderhawk",
    "name": "Walder",
    "surname": "Hawk",
    "email": "hawkwalder@gmail.com",
    "phone": "0978612345",
    "password": "1111",
    "role": "admin"
}
###
POST http://localhost:3001/api/users/
content-type: application/json

{
    "username": "amanzhelam",
    "name": "Anzhelika",
    "surname": "Buldenko",
    "email": "amanzhelam@gmail.com",
    "phone": "0979910020",
    "password": "rfrfirf",
    "role": "admin"
}

###
POST http://localhost:3001/api/users/
content-type: application/json

{
    "username": "babiychuk",
    "name": "Anastasiia",
    "surname": "Babiychuk",
    "email": "abab@gmail.com",
    "phone": "0978612347",
    "password": "password",
    "role": "trainer"
}
###
POST http://localhost:3001/api/users/
content-type: application/json

{
    "username": "katekuk",
    "name": "Kate",
    "surname": "Kuk",
    "email": "kkuk@gmail.com",
    "phone": "0978612349",
    "password": "pass",
    "role": "client"
}
###
POST http://localhost:3001/api/login/
content-type: application/json

{
    "username": "walderhawk",
    "password": "1111"
}

###
POST http://localhost:3001/api/login/
content-type: application/json

{
    "username": "bulbab",
    "password": "1111"
}

###
GET http://localhost:3001/api/training-sessions/
###
POST http://localhost:3001/api/training-sessions/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IndhbGRlcmhhd2siLCJpZCI6IjY1NDIzN2VlNjAzOTAwYmMzYzNmYTFiMSIsImlhdCI6MTY5ODgzODc5MH0.v2i3swOq6oU6LL_zgK1uKVsubZ3AROUMVT27I_HN7m0

{
    "mode": "month"
}
###
POST http://localhost:3001/api/training-sessions/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IndhbGRlcmhhd2siLCJpZCI6IjY1NDIzN2VlNjAzOTAwYmMzYzNmYTFiMSIsImlhdCI6MTY5ODgzODc5MH0.v2i3swOq6oU6LL_zgK1uKVsubZ3AROUMVT27I_HN7m0

{
    "time": "09:00",
    "day": "Monday",
    "instructor": "Anzhelika",
    "maxCapacity": 8,
    "registeredClients":[]
}
###
PUT http://localhost:3001/api/training-sessions/65423a4f603900bc3c3fa1c8/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IndhbGRlcmhhd2siLCJpZCI6IjY1NDIzN2VlNjAzOTAwYmMzYzNmYTFiMSIsImlhdCI6MTY5ODgzODc5MH0.v2i3swOq6oU6LL_zgK1uKVsubZ3AROUMVT27I_HN7m0

{

    "updateType": "reservation",
    "abonementId": "65423b39603900bc3c3fa22a"
}
###
PUT http://localhost:3001/api/training-sessions/65423a4f603900bc3c3fa1c8/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IndhbGRlcmhhd2siLCJpZCI6IjY1NDIzN2VlNjAzOTAwYmMzYzNmYTFiMSIsImlhdCI6MTY5ODgzODc5MH0.v2i3swOq6oU6LL_zgK1uKVsubZ3AROUMVT27I_HN7m0

{

    "updateType": "cancellation",
    "abonementId": "65423b39603900bc3c3fa22a"
}
###
DELETE http://localhost:3001/api/training-sessions/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IndhbGRlcmhhd2siLCJpZCI6IjY1NDIzN2VlNjAzOTAwYmMzYzNmYTFiMSIsImlhdCI6MTY5ODgzODc5MH0.v2i3swOq6oU6LL_zgK1uKVsubZ3AROUMVT27I_HN7m0
###