const predefinedSchedule = [
  {
    day: "Monday",
    time: "09:00",
    type: "Stretching",
    instructor: "Anzhelika",
    maxCapacity: 8,
  },
  {
    day: "Monday",
    time: "10:00",
    type: "Healthy Back",
    instructor: "Anzhelika",
    maxCapacity: 8,
  },
  {
    day: "Monday",
    time: "11:00",
    type: "ABS",
    instructor: "Anzhelika",
    maxCapacity: 8,
  },
  {
    day: "Monday",
    time: "12:00",
    type: "Fly Stretching",
    instructor: "Anzhelika",
    maxCapacity: 8,
  },
  {
    day: "Monday",
    time: "18:00",
    type: "Healthy Back",
    instructor: "Anzhelika",
    maxCapacity: 8,
  },
  {
    day: "Monday",
    time: "19:00",
    type: "Tabata",
    instructor: "Anzhelika",
    maxCapacity: 8,
  },
  {
    day: "Monday",
    time: "20:00",
    type: "Fly Yoga",
    instructor: "Anzhelika",
    maxCapacity: 8,
  },
  {
    day: "Tuesday",
    time: "09:00",
    type: "Pilates",
    instructor: "Valeriya",
    maxCapacity: 8,
  },
  {
    day: "Tuesday",
    time: "10:00",
    type: "Functional",
    instructor: "Valeriya",
    maxCapacity: 8,
  },
  {
    day: "Tuesday",
    time: "11:00",
    type: "Yoga",
    instructor: "Valeriya",
    maxCapacity: 8,
  },
  {
    day: "Tuesday",
    time: "12:00",
    type: "Tabata",
    instructor: "Valeriya",
    maxCapacity: 8,
  },
  {
    day: "Tuesday",
    time: "16:00",
    type: "Fly Kids (11-16)",
    instructor: "Anastasiya B",
    maxCapacity: 8,
  },
  {
    day: "Tuesday",
    time: "17:00",
    type: "Fly Kids (6-10)",
    instructor: "Anastasiya B",
    maxCapacity: 8,
  },
  {
    day: "Tuesday",
    time: "18:00",
    type: "Gymnastics",
    instructor: "Anastasiya B",
    maxCapacity: 8,
  },
  {
    day: "Tuesday",
    time: "19:00",
    type: "Functional",
    instructor: "Anastasiya B",
    maxCapacity: 8,
  },
  {
    day: "Tuesday",
    time: "20:00",
    type: "Fly Stretching",
    instructor: "Anastasiya B",
    maxCapacity: 8,
  },
  {
    day: "Wednesday",
    time: "09:00",
    type: "Stretching",
    instructor: "Anzhelika",
    maxCapacity: 8,
  },
  {
    day: "Wednesday",
    time: "10:00",
    type: "Healthy Back",
    instructor: "Anzhelika",
    maxCapacity: 8,
  },
  {
    day: "Wednesday",
    time: "11:00",
    type: "ABS",
    instructor: "Anzhelika",
    maxCapacity: 8,
  },
  {
    day: "Wednesday",
    time: "12:00",
    type: "Fly Stretching",
    instructor: "Anzhelika",
    maxCapacity: 8,
  },
  {
    day: "Wednesday",
    time: "18:00",
    type: "Heels Basic",
    instructor: "Anastasiya T",
    maxCapacity: 8,
  },
  {
    day: "Wednesday",
    time: "19:00",
    type: "Heels Pro",
    instructor: "Anastasiya T",
    maxCapacity: 8,
  },
  {
    day: "Wednesday",
    time: "20:00",
    type: "Stretching",
    instructor: "Anastasiya T",
    maxCapacity: 8,
  },
  {
    day: "Thursday",
    time: "09:00",
    type: "Pilates",
    instructor: "Valeriya",
    maxCapacity: 8,
  },
  {
    day: "Thursday",
    time: "10:00",
    type: "Functional",
    instructor: "Valeriya",
    maxCapacity: 8,
  },
  {
    day: "Thursday",
    time: "11:00",
    type: "Yoga",
    instructor: "Valeriya",
    maxCapacity: 8,
  },
  {
    day: "Thursday",
    time: "12:00",
    type: "Tabata",
    instructor: "Valeriya",
    maxCapacity: 8,
  },
  {
    day: "Thursday",
    time: "16:00",
    type: "Fly Kids (11-16)",
    instructor: "Anastasiya B",
    maxCapacity: 8,
  },
  {
    day: "Thursday",
    time: "17:00",
    type: "Fly Kids (6-10)",
    instructor: "Anastasiya B",
    maxCapacity: 8,
  },
  {
    day: "Thursday",
    time: "18:00",
    type: "Gymnastics",
    instructor: "Anastasiya B",
    maxCapacity: 8,
  },
  {
    day: "Thursday",
    time: "19:00",
    type: "Functional",
    instructor: "Anastasiya B",
    maxCapacity: 8,
  },
  {
    day: "Thursday",
    time: "20:00",
    type: "Fly Stretching",
    instructor: "Anastasiya B",
    maxCapacity: 8,
  },
  {
    day: "Friday",
    time: "09:00",
    type: "Stretching",
    instructor: "Anzhelika",
    maxCapacity: 8,
  },
  {
    day: "Friday",
    time: "10:00",
    type: "Healthy Back",
    instructor: "Anzhelika",
    maxCapacity: 8,
  },
  {
    day: "Friday",
    time: "11:00",
    type: "ABS",
    instructor: "Anzhelika",
    maxCapacity: 8,
  },
  {
    day: "Friday",
    time: "12:00",
    type: "Fly Stretching",
    instructor: "Anzhelika",
    maxCapacity: 8,
  },
  {
    day: "Friday",
    time: "18:00",
    type: "Healthy Back",
    instructor: "Anzhelika",
    maxCapacity: 8,
  },
  {
    day: "Friday",
    time: "19:00",
    type: "Tabata",
    instructor: "Anzhelika",
    maxCapacity: 8,
  },
  {
    day: "Friday",
    time: "20:00",
    type: "Fly Yoga",
    instructor: "Anzhelika",
    maxCapacity: 8,
  },
  {
    day: "Saturday",
    time: "10:00",
    type: "Pilates",
    instructor: "Anastasiya B",
    maxCapacity: 8,
  },
  {
    day: "Saturday",
    time: "11:00",
    type: "Functional",
    instructor: "Anastasiya B",
    maxCapacity: 8,
  },
  {
    day: "Saturday",
    time: "12:00",
    type: "Fly Stretching",
    instructor: "Anastasiya B",
    maxCapacity: 8,
  },
  {
    day: "Saturday",
    time: "13:00",
    type: "Fly Kids (11-16)",
    instructor: "Anastasiya B",
    maxCapacity: 8,
  },
  {
    day: "Saturday",
    time: "14:00",
    type: "Fly Kids (6-10)",
    instructor: "Anastasiya B",
    maxCapacity: 8,
  },
  {
    day: "Saturday",
    time: "15:00",
    type: "Gymnastics",
    instructor: "Anastasiya B",
    maxCapacity: 8,
  },
  {
    day: "Saturday",
    time: "17:00",
    type: "Heels Basic",
    instructor: "Anastasiya T",
    maxCapacity: 8,
  },
  {
    day: "Saturday",
    time: "18:00",
    type: "Heels Pro",
    instructor: "Anastasiya T",
    maxCapacity: 8,
  },
  {
    day: "Saturday",
    time: "19:00",
    type: "Stretching",
    instructor: "Anastasiya T",
    maxCapacity: 8,
  },
];

module.exports = predefinedSchedule;
