# --------------------------------------------------------AUTH
GET http://localhost:3001/activation/$2b$04$ipmj84RyGaoVdkUPsqU.He
content-type: application/json
###
POST http://localhost:3001/registration
content-type: application/json

{
  "firstName": "vlad",
  "lastName": "Bul",
  "email": "vladbuldenko@gmail.com",
  "phone": "0978612121",
  "password": "123456",
  "role": "client"
}
###
###
POST http://localhost:3001/login
content-type: application/json

{
  "email": "john.doe@example.com",
  "password": "123456"
}
###
###
GET http://localhost:3001/refresh
content-type: application/json
###
POST http://localhost:3001/forgotPassword
content-type: application/json

{
  "email": "vladbuldenko@gmail.com"
}
###
###
POST http://localhost:3001/resetPassword/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZmlyc3ROYW1lIjoidmxhZCIsImxhc3ROYW1lIjoiQnVsIiwiZW1haWwiOiJ2bGFkYnVsZGVua29AZ21haWwuY29tIiwiaWF0IjoxNzI1MDk3NDk5LCJleHAiOjE3MjUxMDEwOTl9.MB53R4GyrdTqRSzf8BMgLjw7t_mZCyEsi6wwQb1h5wI
content-type: application/json

{
  "password": "123456",
  "passwordConfirm": "123456"
}
###

# --------------------------------------------------------USERS
GET http://localhost:3001/users/profile
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZmlyc3ROYW1lIjoidmxhZCIsImxhc3ROYW1lIjoiQnVsIiwiZW1haWwiOiJ2bGFkYnVsZGVua29AZ21haWwuY29tIiwicm9sZSI6ImNsaWVudCIsImlhdCI6MTcyNTI5NDc3NywiZXhwIjoxNzI1MzgxMTc3fQ.kXaQpx7q6MVjt11jnYuTC09CzBOewqQdPYF5W8ETzas
###

# --------------------------------------------------------ABONEMENTS
POST http://localhost:3001/abonements
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZmlyc3ROYW1lIjoidmxhZCIsImxhc3ROYW1lIjoiQnVsIiwiZW1haWwiOiJ2bGFkYnVsZGVua29AZ21haWwuY29tIiwicm9sZSI6ImNsaWVudCIsImlhdCI6MTcyNTI5MDk4MCwiZXhwIjoxNzI1Mjk0NTgwfQ.FaFV2D4mARXVRYyeGCJT4HvASW925XQPfiTY8paI8jg

{
  "clientId": 1,
  "type": "stretching",
  "amount": "4",
  "price": "1700"
}
###
GET http://localhost:3001/abonements/5
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZmlyc3ROYW1lIjoidmxhZCIsImxhc3ROYW1lIjoiQnVsIiwiZW1haWwiOiJ2bGFkYnVsZGVua29AZ21haWwuY29tIiwicm9sZSI6ImNsaWVudCIsImlhdCI6MTcyNTI5NDc3NywiZXhwIjoxNzI1MzgxMTc3fQ.kXaQpx7q6MVjt11jnYuTC09CzBOewqQdPYF5W8ETzas

###

# --------------------------------------------------------TRAININGS
POST http://localhost:3001/trainings
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZmlyc3ROYW1lIjoiSm9obiIsImxhc3ROYW1lIjoiRG9lIiwiZW1haWwiOiJqb2huLmRvZUBleGFtcGxlLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcyNTI5NzQ1NiwiZXhwIjoxNzI1MzgzODU2fQ.ut_x_fql6evG0-jstPzwl3I53Tt411KHGc3AhDHu_OY

{
  "instructorId": 2,
  "type": "Stretching",
  "capacity": "8",
  "price": "1700",
  "day": "Monday",
  "time": "16:00",
  "date": "2024-09-02T17:22:22.961Z"
}
###
GET http://localhost:3001/trainings/2
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZmlyc3ROYW1lIjoidmxhZCIsImxhc3ROYW1lIjoiQnVsIiwiZW1haWwiOiJ2bGFkYnVsZGVua29AZ21haWwuY29tIiwicm9sZSI6ImNsaWVudCIsImlhdCI6MTcyNTI5NDc3NywiZXhwIjoxNzI1MzgxMTc3fQ.kXaQpx7q6MVjt11jnYuTC09CzBOewqQdPYF5W8ETzas

###