export enum NavLinks {
  Home = "/",
  Services = "services",
  Schedule = "schedule",
  Prices = "prices",
  Contacts = "contacts",
  Login = "sign-in",
  SignUp = "sign-up",
  Activate = "activation/:activationToken",
  ForgotPassword = "forgot-password",
  ResetPassword = "reset-password",
  Account = "account",
  Purchases = "purchases",
  Users = "users",
  Team = "team",
  Clients = "clients",
  Settings = "settings",
  CheckEmail = "check-email",
  ScheduleEditor = "schedule-editor",
}
